from typing import Dict
import numpy as np
from nvmolkit.types import AsyncGpuResult

def CrossTanimotoSimilarityRawBuffers(fp1: Dict, fp2: Dict) -> AsyncGpuResult: ...

def CrossTanimotoSimilarityCPURawBuffers(fp1: Dict, fp2: Dict) -> np.ndarray: ...

def CrossCosineSimilarityRawBuffers(fp1: Dict, fp2: Dict) -> AsyncGpuResult: ...

def CrossCosineSimilarityCPURawBuffers(fp1: Dict, fp2: Dict) -> np.ndarray: ...