# Instructions for installing build and lint requirements
# These can be run to create a docker file, or individual instructions
# used manually to install the requirements on a local machine.
FROM nvcr.io/nvidia/cuda:12.5.0-devel-ubuntu22.04

RUN apt-get update && \
    apt-get install -y \
      git \
      wget \
      curl \
      clang-15 \
      clang-format-15 \
      clang-tidy-15 \
      libeigen3-dev && \
    rm -rf /var/lib/apt/lists/*




RUN wget https://github.com/Kitware/CMake/releases/download/v3.30.0/cmake-3.30.0-linux-x86_64.tar.gz && \
    tar -zxvf cmake-3.30.0-linux-x86_64.tar.gz && \
    mv cmake-3.30.0-linux-x86_64 /opt/cmake-3.30.0 && \
    ln -s /opt/cmake-3.30.0/bin/* /usr/local/bin/ && \
    rm cmake-3.30.0-linux-x86_64.tar.gz 

# Install latest cppcheck
RUN wget https://github.com/danmar/cppcheck/archive/2.14.2.tar.gz && \
    tar -zxvf 2.14.2.tar.gz && \
    cd cppcheck-2.14.2 && \
    mkdir build && \
    cd build && \
    cmake .. -DUSE_MATCHCOMPILER=ON -DCMAKE_BUILD_TYPE=release && \
    make -j && \
    make install && \
    cd ../../ && rm -rf cppcheck-2.14.2 2.14.2.tar.gz

ENV PATH="/opt/conda/bin:${PATH}"

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-py310_24.4.0-0-Linux-x86_64.sh -O miniconda.sh && \
    bash miniconda.sh -b -p /opt/conda && \
    rm miniconda.sh && \
    conda install -y python=3.10.14 && \
    conda upgrade --all -y && \
    conda clean --all -y


COPY environment.yml.dev /tmp/environment.yml
RUN conda update --all -y \
    && conda env create -y -vv -f /tmp/environment.yml && \
    conda clean --all -y && \
    rm /tmp/environment.yml


SHELL ["conda", "run", "-n", "nvmolkit_dev", "/bin/bash", "-c"]